use strict;
use warnings;
use Time::HiRes qw(sleep);
use Test::WWW::Selenium;
use Test::More "no_plan";
use Test::Exception;

my $sel = Test::WWW::Selenium->new( host => "localhost", 
                                    port => 4444, 
                                    browser => "*chrome", 
                                    browser_url => "http://opac.solr.localhost/" );

$sel->open_ok("/");
$sel->type_ok("transl1", "*:*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“*:* recordtype:biblio” returned 74 results.");
$sel->type_ok("transl1", "alchimie");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("L'alchimiste");
$sel->type_ok("transl1", "routard");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "roudart~");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "routa~");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "str_publisher:Den??l");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "str_publisher:\"Denoël\"");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "str_publisher:Den*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "\"bord assis\"~5");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Sur le bord de la rivière Piedra, je me suis assise et j'ai pleuré");
$sel->type_ok("transl1", "str_publisher:Den* NOT str_author:Bennett*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le routard galactique");
$sel->type_ok("transl1", "date_pubdate:1985*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Sans fin");
$sel->type_ok("transl1", "date_pubdate:\"1988-01-01T00:00:00Z\"");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("La Résurrection de Mozart");
$sel->type_ok("transl1", "date_acqdate:\"2010-08-31T00:00:00Z\"");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Anioutka");
$sel->type_ok("transl1", "echelle");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("10 sur l'échelle de Richter");
