use strict;
use warnings;
use Time::HiRes qw(sleep);
use Test::WWW::Selenium;
use Test::More "no_plan";
use Test::Exception;

my $sel = Test::WWW::Selenium->new( host => "localhost", 
                                    port => 4444, 
                                    browser => "*chrome", 
                                    browser_url => "http://opac.solr.localhost/" );

$sel->open_ok("/");
$sel->type_ok("transl1", "*:*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“*:* recordtype:biblio” returned 100 results.");
$sel->type_ok("transl1", "juge");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le jugement du soir");
$sel->type_ok("transl1", "maudit");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "mautid~");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "maud~");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "str_publisher:Ed.?France-Emp?re");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "str_publisher:\"Ed. France-Empire\"");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "str_publisher:Ed.*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule des maudits");
$sel->type_ok("transl1", "\"nuit jour\"~5");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Mes nuits sont plus belles que vos jours");
$sel->is_text_present_ok("La Nuit, le jour et toutes les autres nuits");
$sel->type_ok("transl1", "str_publisher:Ed* NOT str_author:Atkinson*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“str_publisher:Ed* NOT str_author:Atkinson* recordtype:biblio” returned 3 results");
$sel->type_ok("transl1", "date_pubdate:1999*");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“date_pubdate:1999* recordtype:biblio” returned 13 results");
$sel->type_ok("transl1", "date_pubdate:[1995-01-01T00:00:00Z TO 2000-01-01T00:00:00Z]");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“date_pubdate:[1995-01-01T00:00:00Z TO 2000-01-01T00:00:00Z] recordtype:biblio” returned 57 results");
$sel->type_ok("transl1", "date_acqdate:\"2010-08-31T00:00:00Z\"");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("“date_acqdate:\"2010-08-31T00:00:00Z\" recordtype:biblio” returned 100 results");
$sel->type_ok("transl1", "crepuscule");
$sel->click_ok("searchsubmit");
$sel->wait_for_page_to_load_ok("30000");
$sel->is_text_present_ok("Le crépuscule");
