<h5>Guided reports</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/guided_reports.pl">Guided reports</a></li>
 </ul>

<h5>Statistics wizards</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Acquisitions</a></li>
 <li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Members</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catalogue</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulation</a></li>
 <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Serials</a></li>
 <li><a href="/cgi-bin/koha/reports/reserves_stats.pl">Reserves</a></li> 
 </ul>


 <h5>Top lists</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Members with the most issues</a></li>
 <li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-circulated items</a></li>
 </ul>
 
 <h5>Inactive</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Members who haven't borrowed anything</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items with no issues</a></li>
 </ul>


 <h5>Other</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/itemslost.pl">Lost items</a></li>
 <li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalog by item type</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Average loan time</a></li>
 </ul>
