<select class="advsearch" name="idx">
    <option value="kw">Keyword</option>
    <option value="au">Author</option>
    <option value="au,phr">&nbsp;&nbsp;&nbsp;&nbsp; Author as Phrase</option>
    <option value="cpn">&nbsp;&nbsp;&nbsp;&nbsp; Corporate Name</option>
    <option value="cpn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Corporate Name as Phrase</option>
    <option value="pn">&nbsp;&nbsp;&nbsp;&nbsp; Personal Name</option>
    <option value="pn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Personal Name as Phrase</option>
    <option value="ti">Title</option>
    <option value="ti,phr">&nbsp;&nbsp;&nbsp;&nbsp; Title as phrase</option>
    <option value="se">&nbsp;&nbsp;&nbsp;&nbsp; Series title</option>
    <option value="su">Subject</option>
    <option value="su,phr">&nbsp;&nbsp;&nbsp;&nbsp; Subject as phrase</option>
    <option value="bc">Barcode</option>
    <option value="sn">Standard Number</option>
    <option value="nb">&nbsp;&nbsp;&nbsp;&nbsp; ISBN</option>
    <option value="ns">&nbsp;&nbsp;&nbsp;&nbsp; ISSN</option>
    <option value="callnum">&nbsp;&nbsp;&nbsp;&nbsp; Call number</option>
    <option value="ln,rtrn">Language</option>
    <option value="ab">Abstract</option>
    <option value="nt">Notes/Comments</option>
    <option value="cn-class,phr">Bulletin</option>
    <option value="pb">Publisher</option>
    <option value="pl">Publisher location</option>
    <option value="yr">Publication date (yyyy)</option>
    <option value="acqdate">Acquisition date (yyyy-mm-dd)</option>
</select>
